import matplotlib.pyplot as plt
import numpy as np

oceanthickness = np.load(r".\Europa Models\oceanthickness.npy")
layerthickness = np.load(r".\Europa Models\layerthickness.npy")
layerdepth = np.load(r".\Europa Models\layerdepth.npy")
layerconductivity = np.load(r".\Europa Models\layerconductivity.npy")
oceanconductivity = np.load(r".\Europa Models\oceanconductivity.npy")
shellthickness = np.load(r".\Europa Models\Iceshellthickness.npy")

plt.subplot(2,3,1)
plt.plot(oceanthickness[0], oceanthickness[1], label='40')
plt.plot(oceanthickness[0], oceanthickness[2], label='60')
plt.plot(oceanthickness[0], oceanthickness[3], label='100')
plt.plot(oceanthickness[0], oceanthickness[4], label='160')
plt.plot(oceanthickness[0], oceanthickness[5], label='250')
plt.xscale('log')
plt.yscale('log')
plt.xlabel('Frequency [Hz]')
plt.ylabel('Apparent Conductivity [S/m]')
plt.title("Ocean Thickness [km]")
plt.xlim(10**(-6), 10)
plt.ylim(10**(-2), 10)
plt.axvspan(10**(-2.5), 100, color='lightgrey')
plt.axvline(x=4.3*10**(-7), color='black', linestyle='--')
plt.axvline(x=3.3*10**(-6), color='black', linestyle='--')
plt.axvline(x=2.5*10**(-5), color='black', linestyle='--')
plt.axvline(x=4.9*10**(-5), color='black', linestyle='--')
plt.axvline(x=7.4*10**(-5), color='black', linestyle='--')
plt.legend()

plt.subplot(2,3,2)
plt.plot(oceanconductivity[0], oceanconductivity[1], label='0.2')
plt.plot(oceanconductivity[0], oceanconductivity[2], label='0.5')
plt.plot(oceanconductivity[0], oceanconductivity[3], label='1')
plt.plot(oceanconductivity[0], oceanconductivity[4], label='2')
plt.plot(oceanconductivity[0], oceanconductivity[5], label='5')
plt.xscale('log')
plt.yscale('log')
plt.xlabel('Frequency [Hz]')
plt.ylabel('Apparent Conductivity [S/m]')
plt.title("Ocean Conductivity [S/m]")
plt.xlim(10**(-6), 10)
plt.ylim(10**(-2), 10)
plt.axvspan(10**(-2.5), 100, color='lightgrey')
plt.axvline(x=4.3*10**(-7), color='black', linestyle='--')
plt.axvline(x=3.3*10**(-6), color='black', linestyle='--')
plt.axvline(x=2.5*10**(-5), color='black', linestyle='--')
plt.axvline(x=4.9*10**(-5), color='black', linestyle='--')
plt.axvline(x=7.4*10**(-5), color='black', linestyle='--')
plt.legend()

plt.subplot(2,3,3)
plt.plot(shellthickness[0], shellthickness[1], label='2')
plt.plot(shellthickness[0], shellthickness[2], label='5')
plt.plot(shellthickness[0], shellthickness[3], label='10')
plt.plot(shellthickness[0], shellthickness[4], label='20')
plt.plot(shellthickness[0], shellthickness[5], label='50')
plt.xscale('log')
plt.yscale('log')
plt.xlabel('Frequency [Hz]')
plt.ylabel('Apparent Conductivity [S/m]')
plt.title("Ice-Shell Thickness [km]")
plt.xlim(10**(-6), 10)
plt.ylim(10**(-4), 10)
plt.axvspan(10**(-2.5), 100, color='lightgrey')
plt.axvline(x=4.3*10**(-7), color='black', linestyle='--')
plt.axvline(x=3.3*10**(-6), color='black', linestyle='--')
plt.axvline(x=2.5*10**(-5), color='black', linestyle='--')
plt.axvline(x=4.9*10**(-5), color='black', linestyle='--')
plt.axvline(x=7.4*10**(-5), color='black', linestyle='--')
plt.legend()

plt.subplot(2,3,4)
plt.plot(layerdepth[0], layerdepth[1], label='0.75')
plt.plot(layerdepth[0], layerdepth[2], label='1.25')
plt.plot(layerdepth[0], layerdepth[3], label='2')
plt.plot(layerdepth[0], layerdepth[4], label='3')
plt.plot(layerdepth[0], layerdepth[5], label='5')
plt.xscale('log')
plt.yscale('log')
plt.xlabel('Frequency [Hz]')
plt.ylabel('Apparent Conductivity [S/m]')
plt.title("Layer Depth [km]")
plt.xlim(10**(-6), 10)
plt.ylim(10**(-4), 10)
plt.axvspan(10**(-2.5), 100, color='lightgrey')
plt.axvline(x=4.3*10**(-7), color='black', linestyle='--')
plt.axvline(x=3.3*10**(-6), color='black', linestyle='--')
plt.axvline(x=2.5*10**(-5), color='black', linestyle='--')
plt.axvline(x=4.9*10**(-5), color='black', linestyle='--')
plt.axvline(x=7.4*10**(-5), color='black', linestyle='--')
plt.legend()

plt.subplot(2,3,5)
plt.plot(layerthickness[0], layerthickness[1], label='0.1')
plt.plot(layerthickness[0], layerthickness[2], label='0.5')
plt.plot(layerthickness[0], layerthickness[3], label='1')
plt.plot(layerthickness[0], layerthickness[4], label='2')
plt.plot(layerthickness[0], layerthickness[5], label='4')
plt.xscale('log')
plt.yscale('log')
plt.xlabel('Frequency [Hz]')
plt.ylabel('Apparent Conductivity [S/m]')
plt.title("Layer Thickness [km]")
plt.xlim(10**(-6), 10)
plt.ylim(10**(-4), 10)
plt.axvspan(10**(-2.5), 100, color='lightgrey')
plt.axvline(x=4.3*10**(-7), color='black', linestyle='--')
plt.axvline(x=3.3*10**(-6), color='black', linestyle='--')
plt.axvline(x=2.5*10**(-5), color='black', linestyle='--')
plt.axvline(x=4.9*10**(-5), color='black', linestyle='--')
plt.axvline(x=7.4*10**(-5), color='black', linestyle='--')
plt.legend()

plt.subplot(2,3,6)
plt.plot(layerconductivity[0], layerconductivity[1], label='0.001')
plt.plot(layerconductivity[0], layerconductivity[2], label='0.01')
plt.plot(layerconductivity[0], layerconductivity[3], label='0.1')
plt.plot(layerconductivity[0], layerconductivity[4], label='1')
plt.plot(layerconductivity[0], layerconductivity[5], label='5')
plt.xscale('log')
plt.yscale('log')
plt.xlabel('Frequency [Hz]')
plt.ylabel('Apparent Conductivity [S/m]')
plt.title("Layer Conductivity [S/m]")
plt.xlim(10**(-6), 10)
plt.ylim(10**(-4), 10)
plt.axvspan(10**(-2.5), 100, color='lightgrey')
plt.axvline(x=4.3*10**(-7), color='black', linestyle='--')
plt.axvline(x=3.3*10**(-6), color='black', linestyle='--')
plt.axvline(x=2.5*10**(-5), color='black', linestyle='--')
plt.axvline(x=4.9*10**(-5), color='black', linestyle='--')
plt.axvline(x=7.4*10**(-5), color='black', linestyle='--')
plt.legend()

plt.suptitle("Diagnostic Europa Induction Curves", fontsize= 22)
plt.show()